#!/usr/bin/env python3

import sys
import os
from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QUrl
from PySide6.QtGui import QIcon
from PySide6.QtQml import QQmlApplicationEngine

import gettext
gettext.textdomain("lliurex-flavours-selector")
_ = gettext.gettext

try:
	print("  [LliureX-Flavours-Selector]: Checking root")
	f=open("/var/run/LliurexFlavoursSelector.token","w")
	f.close()
	os.remove("/var/run/LliurexFlavoursSelector.token")

except:
	print("  [LliurexFlavoursSelector]: No administration privileges")
	msg=_("You need administration privileges to run this application.")
	cmd='kdialog --title "Lliurex-Flavours-Selector" --icon "zero-lliurex-flavours.svg" --sorry "%s"'%(msg)
	os.system(cmd)
	sys.exit(1)

from lliurexflavourselector.Core import Core

if os.geteuid()==0:
	os.environ["XDG_CURRENT_DESKTOP"]="KDE"

icons_paths=["/usr/share/icons","/usr/local/share/icons"]
QIcon.setThemeName("breeze")

c=Core.get_core()

app = QApplication(sys.argv)
app.setDesktopFileName("zero-lliurex-flavours")
engine=QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
mainStackBridge=c.mainStack
flavourStackBridge=c.flavourStack
context.setContextProperty('mainStackBridge',mainStackBridge)
context.setContextProperty('flavourStackBridge',flavourStackBridge)

url = QUrl("/usr/lib/python3.12/dist-packages/lliurexflavourselector/rsrc/lliurex-flavours-selector.qml")

engine.load(url)

if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(app.quit)
ret=app.exec()
del engine
del app
sys.exit(ret)
