#!/usr/bin/env python3

import sys
import os
from PyQt5.QtWidgets import QApplication
from lliurexflavourselector import Core


app = QApplication(sys.argv)
c=Core.Core.get_core()
window =c.mainWindow
sys.exit(app.exec_()) 