#!/usr/bin/env python3

import sys
import os
import subprocess
from PyQt5.QtWidgets import QApplication
from lliurexflavourselectorlegacy import Core
import gettext
gettext.textdomain("lliurex-flavours-selector-legacy")
_ = gettext.gettext

def canRun():

	#normalizedNetworkFlavours=["adi","lab-pro","lab-alu","wifi-alu"]
	flavoursInstalled=[]
	canRun=True
	result=[canRun,""]

	cmd="lliurex-version"
	p=subprocess.Popen(cmd,shell=True,stdout=subprocess.PIPE)
	pout=p.communicate()[0]
	ret=pout.decode().split(',')


	for item in ret:
		if item!="edu":
			flavoursInstalled.append(item.strip())

	for item in flavoursInstalled:
		if "adi" in item.strip():
			item="adi"
			canRun=False
			break
		elif "alu" in item.strip():
			item="lab-alu"
			canRun=False
		elif "pro" in item.strip():
			item="lab-pro"
			canRun=False
		elif 'wifi' in item.strip():
			item="wifi-alu"
			canRun=False
			break

	result=[canRun,item]

	return result

#def canRun

try:
	print("  [LliureX-Flavours-Selector-Legacy]: Checking root")
	f=open("/var/run/LliurexFlavoursSelectorLegacy.token","w")
	f.close()
	os.remove("/var/run/LliurexFlavoursSelectorLegacy.token")

except:
	print("  [Lliurex-Flavours-Selector-Legacy]: No administration privileges")
	msg=_("You need administration privileges to run this application.")
	cmd='kdialog --title "Lliurex-Flavours-Selector-Legacy" --icon "zero-lliurex-flavours-legacy.svg" --sorry "%s"'%(msg)
	os.system(cmd)
	sys.exit(1)


canLaunch=canRun()

if canLaunch[0]:
	app = QApplication(sys.argv)
	c=Core.Core.get_core()
	window =c.mainWindow
	sys.exit(app.exec_())
else:
	msg=_("The device is configured as %s for use in a classroom with a standard network.\nThis configuration is not compatible with Flavour Selector Legacy.\nUninstall LLIUREX-META-%s and try again."%(canLaunch[1].upper(),canLaunch[1].upper()))
	cmd='kdialog --title "Lliurex Flavours Selector Legacy" --icon "zero-lliurex-flavours-legacy" --sorry "%s"'%(msg)
	os.system(cmd)
	sys.exit(1)
